// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Favorite        *favorite
	Property        *property
	PropertyPhoto   *propertyPhoto
	Rating          *rating
	SchemaMigration *schemaMigration
	User            *user
	Visit           *visit
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Favorite = &Q.Favorite
	Property = &Q.Property
	PropertyPhoto = &Q.PropertyPhoto
	Rating = &Q.Rating
	SchemaMigration = &Q.SchemaMigration
	User = &Q.User
	Visit = &Q.Visit
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Favorite:        newFavorite(db, opts...),
		Property:        newProperty(db, opts...),
		PropertyPhoto:   newPropertyPhoto(db, opts...),
		Rating:          newRating(db, opts...),
		SchemaMigration: newSchemaMigration(db, opts...),
		User:            newUser(db, opts...),
		Visit:           newVisit(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Favorite        favorite
	Property        property
	PropertyPhoto   propertyPhoto
	Rating          rating
	SchemaMigration schemaMigration
	User            user
	Visit           visit
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Favorite:        q.Favorite.clone(db),
		Property:        q.Property.clone(db),
		PropertyPhoto:   q.PropertyPhoto.clone(db),
		Rating:          q.Rating.clone(db),
		SchemaMigration: q.SchemaMigration.clone(db),
		User:            q.User.clone(db),
		Visit:           q.Visit.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Favorite:        q.Favorite.replaceDB(db),
		Property:        q.Property.replaceDB(db),
		PropertyPhoto:   q.PropertyPhoto.replaceDB(db),
		Rating:          q.Rating.replaceDB(db),
		SchemaMigration: q.SchemaMigration.replaceDB(db),
		User:            q.User.replaceDB(db),
		Visit:           q.Visit.replaceDB(db),
	}
}

type queryCtx struct {
	Favorite        *favoriteDo
	Property        *propertyDo
	PropertyPhoto   *propertyPhotoDo
	Rating          *ratingDo
	SchemaMigration *schemaMigrationDo
	User            *userDo
	Visit           *visitDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Favorite:        q.Favorite.WithContext(ctx),
		Property:        q.Property.WithContext(ctx),
		PropertyPhoto:   q.PropertyPhoto.WithContext(ctx),
		Rating:          q.Rating.WithContext(ctx),
		SchemaMigration: q.SchemaMigration.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		Visit:           q.Visit.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
