// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"booking.com/internal/db/postgresql/model"
)

func newPropertyPhoto(db *gorm.DB, opts ...gen.DOOption) propertyPhoto {
	_propertyPhoto := propertyPhoto{}

	_propertyPhoto.propertyPhotoDo.UseDB(db, opts...)
	_propertyPhoto.propertyPhotoDo.UseModel(&model.PropertyPhoto{})

	tableName := _propertyPhoto.propertyPhotoDo.TableName()
	_propertyPhoto.ALL = field.NewAsterisk(tableName)
	_propertyPhoto.ID = field.NewInt64(tableName, "id")
	_propertyPhoto.PropertyID = field.NewInt64(tableName, "property_id")
	_propertyPhoto.ImageURL = field.NewString(tableName, "image_url")
	_propertyPhoto.IsPrimary = field.NewBool(tableName, "is_primary")
	_propertyPhoto.CreatedAt = field.NewTime(tableName, "created_at")

	_propertyPhoto.fillFieldMap()

	return _propertyPhoto
}

type propertyPhoto struct {
	propertyPhotoDo

	ALL        field.Asterisk
	ID         field.Int64
	PropertyID field.Int64
	ImageURL   field.String
	IsPrimary  field.Bool
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (p propertyPhoto) Table(newTableName string) *propertyPhoto {
	p.propertyPhotoDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p propertyPhoto) As(alias string) *propertyPhoto {
	p.propertyPhotoDo.DO = *(p.propertyPhotoDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *propertyPhoto) updateTableName(table string) *propertyPhoto {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PropertyID = field.NewInt64(table, "property_id")
	p.ImageURL = field.NewString(table, "image_url")
	p.IsPrimary = field.NewBool(table, "is_primary")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *propertyPhoto) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *propertyPhoto) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["id"] = p.ID
	p.fieldMap["property_id"] = p.PropertyID
	p.fieldMap["image_url"] = p.ImageURL
	p.fieldMap["is_primary"] = p.IsPrimary
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p propertyPhoto) clone(db *gorm.DB) propertyPhoto {
	p.propertyPhotoDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p propertyPhoto) replaceDB(db *gorm.DB) propertyPhoto {
	p.propertyPhotoDo.ReplaceDB(db)
	return p
}

type propertyPhotoDo struct{ gen.DO }

func (p propertyPhotoDo) Debug() *propertyPhotoDo {
	return p.withDO(p.DO.Debug())
}

func (p propertyPhotoDo) WithContext(ctx context.Context) *propertyPhotoDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p propertyPhotoDo) ReadDB() *propertyPhotoDo {
	return p.Clauses(dbresolver.Read)
}

func (p propertyPhotoDo) WriteDB() *propertyPhotoDo {
	return p.Clauses(dbresolver.Write)
}

func (p propertyPhotoDo) Session(config *gorm.Session) *propertyPhotoDo {
	return p.withDO(p.DO.Session(config))
}

func (p propertyPhotoDo) Clauses(conds ...clause.Expression) *propertyPhotoDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p propertyPhotoDo) Returning(value interface{}, columns ...string) *propertyPhotoDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p propertyPhotoDo) Not(conds ...gen.Condition) *propertyPhotoDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p propertyPhotoDo) Or(conds ...gen.Condition) *propertyPhotoDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p propertyPhotoDo) Select(conds ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p propertyPhotoDo) Where(conds ...gen.Condition) *propertyPhotoDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p propertyPhotoDo) Order(conds ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p propertyPhotoDo) Distinct(cols ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p propertyPhotoDo) Omit(cols ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p propertyPhotoDo) Join(table schema.Tabler, on ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p propertyPhotoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p propertyPhotoDo) RightJoin(table schema.Tabler, on ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p propertyPhotoDo) Group(cols ...field.Expr) *propertyPhotoDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p propertyPhotoDo) Having(conds ...gen.Condition) *propertyPhotoDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p propertyPhotoDo) Limit(limit int) *propertyPhotoDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p propertyPhotoDo) Offset(offset int) *propertyPhotoDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p propertyPhotoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *propertyPhotoDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p propertyPhotoDo) Unscoped() *propertyPhotoDo {
	return p.withDO(p.DO.Unscoped())
}

func (p propertyPhotoDo) Create(values ...*model.PropertyPhoto) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p propertyPhotoDo) CreateInBatches(values []*model.PropertyPhoto, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p propertyPhotoDo) Save(values ...*model.PropertyPhoto) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p propertyPhotoDo) First() (*model.PropertyPhoto, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyPhoto), nil
	}
}

func (p propertyPhotoDo) Take() (*model.PropertyPhoto, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyPhoto), nil
	}
}

func (p propertyPhotoDo) Last() (*model.PropertyPhoto, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyPhoto), nil
	}
}

func (p propertyPhotoDo) Find() ([]*model.PropertyPhoto, error) {
	result, err := p.DO.Find()
	return result.([]*model.PropertyPhoto), err
}

func (p propertyPhotoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PropertyPhoto, err error) {
	buf := make([]*model.PropertyPhoto, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p propertyPhotoDo) FindInBatches(result *[]*model.PropertyPhoto, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p propertyPhotoDo) Attrs(attrs ...field.AssignExpr) *propertyPhotoDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p propertyPhotoDo) Assign(attrs ...field.AssignExpr) *propertyPhotoDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p propertyPhotoDo) Joins(fields ...field.RelationField) *propertyPhotoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p propertyPhotoDo) Preload(fields ...field.RelationField) *propertyPhotoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p propertyPhotoDo) FirstOrInit() (*model.PropertyPhoto, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyPhoto), nil
	}
}

func (p propertyPhotoDo) FirstOrCreate() (*model.PropertyPhoto, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PropertyPhoto), nil
	}
}

func (p propertyPhotoDo) FindByPage(offset int, limit int) (result []*model.PropertyPhoto, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p propertyPhotoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p propertyPhotoDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p propertyPhotoDo) Delete(models ...*model.PropertyPhoto) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *propertyPhotoDo) withDO(do gen.Dao) *propertyPhotoDo {
	p.DO = *do.(*gen.DO)
	return p
}
