// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"booking.com/internal/db/postgresql/model"
)

func newVisit(db *gorm.DB, opts ...gen.DOOption) visit {
	_visit := visit{}

	_visit.visitDo.UseDB(db, opts...)
	_visit.visitDo.UseModel(&model.Visit{})

	tableName := _visit.visitDo.TableName()
	_visit.ALL = field.NewAsterisk(tableName)
	_visit.ID = field.NewInt64(tableName, "id")
	_visit.PropertyID = field.NewInt64(tableName, "property_id")
	_visit.BuyerUsername = field.NewString(tableName, "buyer_username")
	_visit.ScheduledTime = field.NewTime(tableName, "scheduled_time")
	_visit.Status = field.NewString(tableName, "status")
	_visit.RescheduleTime = field.NewTime(tableName, "reschedule_time")
	_visit.PartnerNote = field.NewString(tableName, "partner_note")
	_visit.BuyerNote = field.NewString(tableName, "buyer_note")
	_visit.Deleted = field.NewBool(tableName, "deleted")
	_visit.CreatedAt = field.NewTime(tableName, "created_at")
	_visit.UpdatedAt = field.NewTime(tableName, "updated_at")

	_visit.fillFieldMap()

	return _visit
}

type visit struct {
	visitDo

	ALL            field.Asterisk
	ID             field.Int64
	PropertyID     field.Int64
	BuyerUsername  field.String
	ScheduledTime  field.Time
	Status         field.String
	RescheduleTime field.Time
	PartnerNote    field.String
	BuyerNote      field.String
	Deleted        field.Bool
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (v visit) Table(newTableName string) *visit {
	v.visitDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v visit) As(alias string) *visit {
	v.visitDo.DO = *(v.visitDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *visit) updateTableName(table string) *visit {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.PropertyID = field.NewInt64(table, "property_id")
	v.BuyerUsername = field.NewString(table, "buyer_username")
	v.ScheduledTime = field.NewTime(table, "scheduled_time")
	v.Status = field.NewString(table, "status")
	v.RescheduleTime = field.NewTime(table, "reschedule_time")
	v.PartnerNote = field.NewString(table, "partner_note")
	v.BuyerNote = field.NewString(table, "buyer_note")
	v.Deleted = field.NewBool(table, "deleted")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *visit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *visit) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 11)
	v.fieldMap["id"] = v.ID
	v.fieldMap["property_id"] = v.PropertyID
	v.fieldMap["buyer_username"] = v.BuyerUsername
	v.fieldMap["scheduled_time"] = v.ScheduledTime
	v.fieldMap["status"] = v.Status
	v.fieldMap["reschedule_time"] = v.RescheduleTime
	v.fieldMap["partner_note"] = v.PartnerNote
	v.fieldMap["buyer_note"] = v.BuyerNote
	v.fieldMap["deleted"] = v.Deleted
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v visit) clone(db *gorm.DB) visit {
	v.visitDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v visit) replaceDB(db *gorm.DB) visit {
	v.visitDo.ReplaceDB(db)
	return v
}

type visitDo struct{ gen.DO }

func (v visitDo) Debug() *visitDo {
	return v.withDO(v.DO.Debug())
}

func (v visitDo) WithContext(ctx context.Context) *visitDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v visitDo) ReadDB() *visitDo {
	return v.Clauses(dbresolver.Read)
}

func (v visitDo) WriteDB() *visitDo {
	return v.Clauses(dbresolver.Write)
}

func (v visitDo) Session(config *gorm.Session) *visitDo {
	return v.withDO(v.DO.Session(config))
}

func (v visitDo) Clauses(conds ...clause.Expression) *visitDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v visitDo) Returning(value interface{}, columns ...string) *visitDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v visitDo) Not(conds ...gen.Condition) *visitDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v visitDo) Or(conds ...gen.Condition) *visitDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v visitDo) Select(conds ...field.Expr) *visitDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v visitDo) Where(conds ...gen.Condition) *visitDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v visitDo) Order(conds ...field.Expr) *visitDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v visitDo) Distinct(cols ...field.Expr) *visitDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v visitDo) Omit(cols ...field.Expr) *visitDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v visitDo) Join(table schema.Tabler, on ...field.Expr) *visitDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v visitDo) LeftJoin(table schema.Tabler, on ...field.Expr) *visitDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v visitDo) RightJoin(table schema.Tabler, on ...field.Expr) *visitDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v visitDo) Group(cols ...field.Expr) *visitDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v visitDo) Having(conds ...gen.Condition) *visitDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v visitDo) Limit(limit int) *visitDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v visitDo) Offset(offset int) *visitDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v visitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *visitDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v visitDo) Unscoped() *visitDo {
	return v.withDO(v.DO.Unscoped())
}

func (v visitDo) Create(values ...*model.Visit) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v visitDo) CreateInBatches(values []*model.Visit, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v visitDo) Save(values ...*model.Visit) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v visitDo) First() (*model.Visit, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Visit), nil
	}
}

func (v visitDo) Take() (*model.Visit, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Visit), nil
	}
}

func (v visitDo) Last() (*model.Visit, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Visit), nil
	}
}

func (v visitDo) Find() ([]*model.Visit, error) {
	result, err := v.DO.Find()
	return result.([]*model.Visit), err
}

func (v visitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Visit, err error) {
	buf := make([]*model.Visit, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v visitDo) FindInBatches(result *[]*model.Visit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v visitDo) Attrs(attrs ...field.AssignExpr) *visitDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v visitDo) Assign(attrs ...field.AssignExpr) *visitDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v visitDo) Joins(fields ...field.RelationField) *visitDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v visitDo) Preload(fields ...field.RelationField) *visitDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v visitDo) FirstOrInit() (*model.Visit, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Visit), nil
	}
}

func (v visitDo) FirstOrCreate() (*model.Visit, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Visit), nil
	}
}

func (v visitDo) FindByPage(offset int, limit int) (result []*model.Visit, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v visitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v visitDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v visitDo) Delete(models ...*model.Visit) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *visitDo) withDO(do gen.Dao) *visitDo {
	v.DO = *do.(*gen.DO)
	return v
}
