// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	ID         int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	PropertyID int64     `gorm:"column:property_id;type:bigint;not null" json:"property_id"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
