// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFavorite = "favorites"

// Favorite mapped from table <favorites>
type Favorite struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserUsername string    `gorm:"column:user_username;type:character varying(50);not null" json:"user_username"`
	PropertyID   int64     `gorm:"column:property_id;type:bigint;not null" json:"property_id"`
	Deleted      bool      `gorm:"column:deleted;type:boolean" json:"deleted"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
