// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRating = "ratings"

// Rating mapped from table <ratings>
type Rating struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	PropertyID      int64     `gorm:"column:property_id;type:bigint;not null" json:"property_id"`
	BuyerUsername   string    `gorm:"column:buyer_username;type:character varying(50);not null" json:"buyer_username"`
	PartnerUsername string    `gorm:"column:partner_username;type:character varying(50);not null" json:"partner_username"`
	Rating          int32     `gorm:"column:rating;type:integer" json:"rating"`
	ReviewText      string    `gorm:"column:review_text;type:text" json:"review_text"`
	Deleted         bool      `gorm:"column:deleted;type:boolean" json:"deleted"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Rating's table name
func (*Rating) TableName() string {
	return TableNameRating
}
