// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Email           string    `gorm:"column:email;type:character varying(100);primaryKey" json:"email"`
	FirstName       string    `gorm:"column:first_name;type:character varying(100);not null" json:"first_name"`
	LastName        string    `gorm:"column:last_name;type:character varying(100);not null" json:"last_name"`
	Phone           string    `gorm:"column:phone;type:character varying(20)" json:"phone"`
	PasswordHash    string    `gorm:"column:password_hash;type:character varying(255);not null" json:"password_hash"`
	Salt            string    `gorm:"column:salt;type:character varying(100);not null" json:"salt"`
	ProfilePicURL   string    `gorm:"column:profile_pic_url;type:text" json:"profile_pic_url"`
	Address         string    `gorm:"column:address;type:character varying(255)" json:"address"`
	Role            string    `gorm:"column:role;type:character varying(100);not null" json:"role"`
	IsEmailVerified bool      `gorm:"column:is_email_verified;type:boolean" json:"is_email_verified"`
	IsPhoneVerified bool      `gorm:"column:is_phone_verified;type:boolean" json:"is_phone_verified"`
	RefreshToken    string    `gorm:"column:refresh_token;type:character varying(255)" json:"refresh_token"`
	Deleted         bool      `gorm:"column:deleted;type:boolean" json:"deleted"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
