// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVisit = "visits"

// Visit mapped from table <visits>
type Visit struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	PropertyID     int64     `gorm:"column:property_id;type:bigint;not null" json:"property_id"`
	BuyerUsername  string    `gorm:"column:buyer_username;type:character varying(50);not null" json:"buyer_username"`
	ScheduledTime  time.Time `gorm:"column:scheduled_time;type:timestamp without time zone;not null" json:"scheduled_time"`
	Status         string    `gorm:"column:status;type:character varying(100)" json:"status"`
	RescheduleTime time.Time `gorm:"column:reschedule_time;type:timestamp without time zone" json:"reschedule_time"`
	PartnerNote    string    `gorm:"column:partner_note;type:text" json:"partner_note"`
	BuyerNote      string    `gorm:"column:buyer_note;type:text" json:"buyer_note"`
	Deleted        bool      `gorm:"column:deleted;type:boolean" json:"deleted"`
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Visit's table name
func (*Visit) TableName() string {
	return TableNameVisit
}
